replicatedhq/replicated-installer

install_scripts/templates/common/docker-install.sh
install_scripts/templates/kubernetes-init.sh

This will install docker 1.12 or 1.13 from RHEL's fork of docker. Installing these versions of docker from the docker-engine repo requires using the systemd cgroup driver and also pulls docker-engine-selinux-1705 as a dependency with noisy warnings.

use docker yum repo for kubernetes installs

---

install_scripts/app.py
install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-yml-generate.sh

No longer create Replicated service accounts in default and kube-system
namespace.
All environments have a default service account.

Move ClusterRoleBinding to k8s-yml-generate

---

install_scripts/templates/kubernetes-init.sh

If you run with 
```
curl ... | sudo bash
```
then `${0}` is `bash`, as expected. If you run it with 
```
curl -o install.sh ...
bash install.sh
```
then `${0}` is `install.sh`, which is not what we want to instruct people to run.
This change makes it so we always just instruct folks to `bash -l`, regardless of their shell, which should be fine for pretty much every case.

Always just say bash, don't get fancy with ${0}

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-node-join.sh

I've confirmed that this is idempotent

always start/enable kubelet, even if we skipped package install

---

install_scripts/templates/common/kubernetes.sh

This works for the first install and for subsequent installs, unlike yum
which reports "Error: nothing to do" for reinstalls.

Use RPM to install K8s packages

---

bundles/k8s-containers-v1.9.3/mk-image-cache-lst

When linuxkit parses the reference for images in this repo it gets the
tag as the host/path and fails to get the digest. Prefixing the server
allows linuxkit to parse correctly and find the digest.

specify server of registry image

---

install_scripts/templates/common/docker-install.sh

Amazon seems to be removing old Docker versions from their repos - at time of writing, only 17.12.1ce was available on Amazon Linux 18.03 or 17.09.
```
yum --showduplicates list docker
Available Packages
docker.x86_64  17.12.1ce-1.135.amzn1  amzn-main
```

ignore the version of Docker specified for Amazon Linux

---

install_scripts/templates/common/airgap.sh

Load retraced-processor.tar and similar into Docker before extracting
retraced-bundle.tar, since it contains retraced-processor.tar and
similar.
If someone is upgrading from prior to 2.21.0 and uses the same
directory, both retraced-bundle.tar and the updated single retraced tars
would exist in that directory. With this change, images will be loaded
from both sources.

Load single retraced images before bundle images

---

install_scripts/templates/swarm-worker-join.sh

Replicated versions greater than 2.20 generate scripts with the
daemon-registry-address and ca params set, so the CA will still be
written during install. When installing older pinned versions the CA
will not be set until later when the operator starts on the node.

swarm join does not prompt for CA

---

install_scripts/templates/swarm-init.sh

This follows removing the `replicated_default` network when upgrading Swarm from less than `2.22.0`.

poll until network is gone

---

install_scripts/templates/upstart/replicated-operator.conf
install_scripts/templates/upstart/replicated-ui.conf
install_scripts/templates/upstart/replicated.conf

To avoid "container name still in use" errors, confirm removal success as part of the pre-start script and retry a limited number of times upon failure. Retries should have standard error show in logs (first try does not due to the frequency of "container does not exist" errors)
increase upstart respawn limit timer to avoid infinite loops

Upstart service ensure prior container has been removed

---

install_scripts/templates/docker-install/17-03-ce.sh
install_scripts/templates/docker-install/17-06-ce.sh
install_scripts/templates/docker-install/17-12-ce.sh

Docker is only available in bionic/edge channel at version 18.05.
Docker 17.03, 17.06, and 17.12 install on bionic from xenial channel,
but 1.12 and 1.13 do not work.

install docker on bionic from xenial channel

---

install_scripts/helpers.py
install_scripts/templates/kubernetes-init.sh

Allows installer to disable clearing the terminal page after the AKA install script (or uninstall script) finishes. When the `no-clear` flag is set, terminal scrollback is possible.

aka no-clear flag

---

bundles/k8s-rhel7/Dockerfile
bundles/k8s-rhel7/Makefile
bundles/k8s-ubuntu1604/Dockerfile
bundles/k8s-ubuntu1604/Makefile
install_scripts/app.py
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/common/selinux.sh
install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-node-join.sh
install_scripts/templates/kubernetes-node-upgrade.sh
install_scripts/templates/kubernetes-upgrade.sh

upgrade K8s clusters to v1.11.0
This attempts to follow best practices from
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/.
kubeadm upgrades cannot skip a minor version so upgrading to 1.10.5 must
be completed as the first step before upgrading to 1.11.0.
CoreDNS is not included because of SELinux incompatibilities introduced
in https://github.com/kubernetes/kubernetes/pull/64473/files.
This does not update Replicated to a version compatible with K8s
v1.11.0. The kubernetes-upgrade.sh script should probably be merged with
the kubernetes-init.sh script to accomplish that.
Untested on airgap.

upgrade K8s clusters

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/node-upgrade.sh
install_scripts/templates/kubernetes/yml-generate.sh

Don't publish the dashboard.
Don't grep for google_containers.
Uncomment rook data path.
Fix airgap 1.10.6 images.
Fix upgrade worker airgap bugs.
Preload 1.11.1 on worker for coredns images.
Don't reapply storage class if it exists.

K8s upgrade bug fixes

---

install_scripts/templates/common/kubernetes.sh

This will only have an affect if old airgap bundles get rebuilt.

fix image ids from aka 1.9.3 airgap

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh

timeout takes a duration, but grace-period does not.

kubectl drain timeout duration

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

Since this script may be run to upgrade existing airgap installs and the
size of exiting PVCs provisioned by Rook cannot be edited, include a
check to disable rendering the Replicated PVC yaml it the resource
already exists.

Replicated PVC 100G for airgap installs

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/kubernetes/init.sh

Prevents the need for a GET https://dl.k8s.io/release/stable-1.11.txt
Also retry kubeadm upgrade node config in case K8s API is temporarily unavailable.

pass k8s version to kubeadm init

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/kubernetes/init.sh

The kubeadm alpha phase kubelet write-env-file attempts to lookup the
stable version of k8s and does not have a --kubernetes-version flag to
disable like other commands.
Kubeadm init does not need --kubernetes-version flag - it's specified in
the config file.

generate kubeadm-flags.env file

---

chart/.helmignore
chart/Chart.yaml
chart/templates/_helpers.tpl
chart/templates/clusterrole/clusterrole.yaml
chart/templates/deployment/replicated.yaml
chart/templates/pvc/replicated-premkit-data-volume.yaml
chart/templates/pvc/replicated-pv-claim.yaml
chart/templates/pvc/replicated-statsd-graphite-storage.yaml
chart/templates/service/replicated-ui.yaml
chart/templates/service/replicated.yaml
chart/templates/storageclass/storageclass.yaml
chart/values.yaml

What I Did
------------
- Translate yaml generated from `/kubernetes-yaml-generate` to a Helm chart that exposes the same values
How I Did it
------------
- Translated the following template variables (excluding those related to rook)
| kubernetes template argument | values.yaml                                               |
|------------------------------|-----------------------------------------------------------|
| channel_name                 | .Values.deployment.env.releaseChannel                     |
| replicated_tag               | .Values.deployment.replicated.env.releaseChannel          |
| pv_base_path                 |                                                           |
| log_level                    | .Values.deployment.env.logLevel                           |
| …

Add helm chart for replicated

---

chart/templates/deployment/replicated.yaml
chart/templates/service/replicated-ui.yaml
chart/templates/storageclass/storageclass.yaml
chart/values.yaml

What I Did
------------
- Various fixes for replicated helm chart
How I Did it
------------
- Allow ui to be deployed as LoadBalancer, ClusterIP, or NodePort (default)
- Update replicated image to stable-2.25.2
- Update default noProxyAddress to CIDR 10.96.0.0/12
- Change releaseChannel from default to stable
- Change storageClass from default to standard
- Update K8S_STORAGECLASS env variable to use storageClass from values.yaml

Fixes for replicated helm chart

---

install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/common/selinux.sh
install_scripts/templates/kubernetes/init.sh

Fix the kubernetes-init install script fails on the image "Red Hat
Enterprise Linux for SAP Applications 7.4" in Google cloud.
Use `rpm --upgrade --nodeps` for installing Docker packages, matching
how Kubernetes packages are installed on RHEL.
Remove allowPrivilegeEscalation from CoreDNS yaml; the previous fix of
writing a custom policy fails on this RHEL image.

Fixes for AKA on RHEL7.4

---

install_scripts/templates/kubernetes/init.sh

The getYAMLOpts function runs before the rookDeploy function, so the
CEPH_DASHBOARD_URL was not getting passed to the yaml generator.

fix ceph-dashboard-url missing in yaml opts

---

install_scripts/templates/replicated-2.0.sh

Running install script first without the `http_proxy` parameter and then again with the parameter results in Replicated containers not having the NO_PROXY variable set.
[ch15399]

Set the NO_PROXY variable in Replicated container

---

install_scripts/templates/systemd/replicated-operator.service
install_scripts/templates/systemd/replicated-ui.service
install_scripts/templates/systemd/replicated.service

When a service is updated systemd will do a stop and then start. Because of this the replicated services do not come back up after docker update. This change will cause replicated to start EVERY time docker unit starts. This changes functionality. For example if you stop replicated and then restart docker replicated will come back up. Prior to this change it would only come back up on reboot. In order to stop it for good you will have to disable the service. I think this should be ok since really the replicated service should always be running.

Replicated systemd service not restarting [ch14874]

---

.circleci/config.yml
install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh

Prevent the install from failing after changes like https://launchpad.net/ubuntu/+source/kmod/22-1ubuntu5.1

dpkg in aka install ignores version dependencies

---

install_scripts/app.py

Keep swarm-worker-join as deprecated endpoint

Change endpoint name to swarm-join for the swarm node join script [ch16397]

---

install_scripts/templates/common/docker-install.sh

https://app.clubhouse.io/replicated/story/16892/container-selinux-packages-we-are-referencing-are-no-longer-hosted-on-centos-mirror
container-selinux packages we are referencing are no longer hosted on centos mirror

update centos selinux image urls [ch16892]

---

install_scripts/templates/kubernetes/init.sh

If an upgrade from 1.11 to 1.13 is terminated while on 1.12, the config
file will not be parseable since we only write alpha1 and beta1, but
kubeadm 1.12 only reads alpha2 and alpha3.

init should not verify 1.12 kubeadm config

---

install_scripts/templates/kubernetes/yml-generate.sh
kustomize/overlays/dev/deployment.yaml

Since we use the downward API to lookup the K8s API server address.

always bind daemon to k8s master node

---

install_scripts/templates/common/kubernetes-upgrade.sh

Kubernetes-only installs won't have Replicated in the default namespace.

do not clear default namespcae for k8s-only upgrades

---

install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

This allows for generating yaml that can be applied to an existing non-airgap cluster without labeling any nodes.

existing clusters do not bind daemon pod to node

---

install_scripts/templates/kubernetes/migrate.sh

The certificates generated with the replaced CA won't validate.

remove old certificates before replacing CA

---

install_scripts/templates/kubernetes/migrate.sh

QA revealed a couple different errors that may happen at or after
restarting the replicated-ui container. Ignoring the error of that
operation and sleeping afterward seems to prevent the issue.

sleep after killing ui container

---

install_scripts/templates/kubernetes/migrate.sh
install_scripts/templates/kubernetes/yml-generate.sh
kustomize/overlays/dev/deployment.yaml

Do not purge /var/lib/replicated after migration since it's the default
location for snapshots.
With Rook now using /var/lib/rook, customers can safely remove
/var/lib/replicated as a manual step if they wish.

use default rook dataDirHostPath

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

If a customer upgrades an airgap cluster from before 2.34 there will be workers that don't have docker configured to pull insecurely from the new docker registry. We don't have a chance to run a command on the workers so we must prompt the user to manually configure those nodes.
The prompt looks like this and blocks until the user hits any key.
```
Configure Docker on all worker nodes to use http when pulling from the in-cluster registry before proceeding.
Example /etc/docker/daemon.json:
{
"insecure-registries" ["10.96.0.0/12"]
}
Continue after updating nodes: areed-airgap-worker
```

airgap HA fixes

---

install_scripts/templates/kubernetes/init.sh

This code was removed when we switched back to ipvs, but it's also
needed for load balancer address changes.

restart kube-proxy

---

install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

Every time the kubernetes-init script runs it ensures the storage class exists, without changing it if it does exist. This protects against interruptions immediately after the storage provisioner is deployed but before the storage class is applied.

K8s init resume

---

install_scripts/templates/common/kubernetes.sh

The 1.13.5 common bundle is the only one that has the updated registry
id.

Fix docker tag registry

---

bundles/k8s-containers/mk-image-cache-lst-v1.13.5
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

Use a ClusterIP service so HA airgap can tolerate the loss of any node.
Pre-render the registry service so the Cluster IP can be passed to the Replicated Deployment yaml.
Print the ClusterIP at the end with message about cert SANs.
Also update airgap common images for Rook 1.0 / Ceph v14, which are now separate images.

HA airgap app registry service

---

install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/node-join.sh
install_scripts/templates/kubernetes/yaml/rook-1-0-system.yml
install_scripts/templates/kubernetes/yml-generate.sh

The Rook operator has a bug that takes down the Ceph object store. Scheduling the REK operator on a separate node than the registry will at least avoid the case where the operator cannot be rescheduled after a node failure because its image cannot be pulled from the registry.

disable object store for registry

---

install_scripts/templates/common/kubernetes-upgrade.sh

We now defer upgrading host kubelet package until after node config has
been downloaded so we can't use kubelet to get the version we're
upgrading to.

fix kubelet target version

---

install_scripts/templates/common/kubernetes-upgrade.sh

The kubelet needs to bring up the static kube-apiserver pod before
kubectl can be reliably used.

wait for k8s api after kubelet restart

---

kustomize/base/deployment.yaml

apparently `1` is the only legal value for liveness probe success thresholds: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes

liveness probe success threshold must be 1

---

kustomize/base/deployment.yaml

staging and prod use port 80, not 5000, unlike dev

check the right port

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/node-join.sh
install_scripts/templates/kubernetes/node-upgrade.sh
kustomize/overlays/dev/deployment.yaml

aka.service with an ExecStop script to remove all pods with PVCs attached. Then poll until `lsblk` reports there are no more `rbd` devices on the node.
Still need to add support for non-masters, possibly by calling the flexvolume plugin directly on the host before the rook agent container goes down.

AKA clean shutdown

---

install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/docker-version.sh

No longer pin docker to 18.09 on amazon linux since 20.10.7 is available.

Support for docker 20.10.7 on amazon linux

---

.circleci/config.yml

Fixes build
```
go get github.com/linuxkit/linuxkit/src/cmd/linuxkit
package embed: unrecognized import path "embed" (import path does not begin with hostname)
Makefile:6: recipe for target 'deps' failed
make: *** [deps] Error 1
Exited with code exit status 2
```

go get github.com/linuxkit/linuxkit/src/cmd/linuxkit requires go 1.16

---

install_scripts/app.py
install_scripts/helpers.py

```
$ curl 'https://install-scripts-divolgin.replicated.okteto.dev/docker-compose.yml?log_level=$(pwd)'
....
- LOG_LEVEL=_(pwd)
```
```
divolgin@repldev-dmitriy:~$ curl 'https://install-scripts-divolgin.replicated.okteto.dev/docker-compose.yml?log_level=`pwd`'
...
- LOG_LEVEL='pwd'
```

Don't allow shell argument expansion when generating YAML files

---

install_scripts/templates/replicated-2.0.sh

Even if no other replicated-ui arguments are present, it should become readonly upon upgrade

Ensure replicated-ui becomes readonly on upgrades

---

uwsgi.ini

uWSGI prior to 2.1 does not die on SIGTERM. I believe this is causing the delay between the SIGTERM request coming from k8s and the actual shutdown of the pods.

Add uwsgi die-on-term=true

---

kustomize/overlays/production/disruptionbudget.yaml
kustomize/overlays/staging/disruptionbudget.yaml

Updates Kustomize overlays for PodDisruptionBudgets to meet requirements in EKS 1.25. The API version `policy/v1beta` is deprecated and removed in 1.25.

Upgrade PDBs to policy/v1 prior to EKS upgrade

---

install_scripts/templates/common/docker-install.sh

According to [EOL notice](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/)
- CentOS 8: May 31, 2024 
- CentOS 7: June 30, 2024
As a result, both http://mirror.centos.org/centos/7/extras/x86_64 and http://mirror.centos.org/centos/8/extras/x86_64/os are return 404 based on the EOL date.
Remove them for  failing at the docker install step

fix(installer): remove centos 7 and 8 repo due to eol

---

install_scripts/app.py
install_scripts/helpers.py

Validate query parameters to reduce HTTP 500 noise:
Some bad inputs
```
$ curl http://localhost/operator?replicated_operator_tag=sdfsd -v
...
< HTTP/2 400 
...
Invalid value for replicated_operator_tag: sdfsd
```
```
$ curl http://localhost/api/version -v
...
< HTTP/2 400 
...
no releases for product replicated_v2 and channel api
```
Actual error
```
$ curl http://localhost/operator?replicated_operator_tag=1.2.3 -v
...
< HTTP/2 500 
...
Internal Server Error
```

Return 400 on bad requests
