bundles/k8s-containers-v1.9.3/README.md

Fix typo of Kubernetes and remove whitespace

fix misspelling of Kubernetes

---

install_scripts/app.py
install_scripts/templates/replicated-2.0-uninstall.sh
src/pip-delete-this-directory.txt

This is the replicated uninstall script.

Replicated Uninstall Script

---

bundles/docker-rhel74/Makefile
bundles/k8s-rhel7/Makefile

This reverts commit bb9ffeb97e2dd609acbeb5fce475296947d61a4c.

Revert "airgap bundles are public"

---

install_scripts/app.py
install_scripts/templates/kubernetes-yml-generate.sh

storage_class (default is 'default')
host_path_provisioner (True)
service_type ('NodePort')
Also update api versions for Kubernetes 1.9

params for existing kubernetes clusters

---

install_scripts/templates/kubernetes-init.sh

It's defined in common/kubernetes.sh

installK8sComponents dupe

---

install_scripts/templates/common/airgap.sh
install_scripts/templates/kubernetes-node-join.sh
install_scripts/templates/kubernetes-yml-generate.sh
install_scripts/templates/swarm-worker-join.sh

Factor daemon registry and ca prompts out of Swarm join so they can be used in K8s join.
Make Replicated services NodePort services.

k8s node join daemon address and ca

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes-node-join.sh
install_scripts/templates/kubernetes-yml-generate.sh

Label the daemon node and for airgap installs bind the daemon to that node so that the airgap package path doesn't break.

K8s airgap node

---

bundles/k8s-containers-v1.9.3/Makefile
bundles/k8s-containers-v1.9.3/mk-image-cache-lst
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes-init.sh

Reset param uninstalls all Kubernetes components.

Kubernetes-only install waits for kube service pods

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes-init.sh

restart docker after rpm --upgrade --force

pre-delete k8s resources with pvs

---

Makefile
install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/docker-version.sh

Makefile improvements & fixed Docker version installed on Amazon Linux

starting with the obvious fixes

---

install_scripts/templates/kubernetes-init.sh

Load them after the kubernetes-only early termination step.

postpone loading Replicated images in airgap

---

install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-node-join.sh
install_scripts/templates/kubernetes-yml-generate.sh

This reverts commit 12cedae947e361cece1ec7a36bd7292131270e53, reversing
changes made to d801319a3187fdc225f85a3c41101e9d428caad0.

Revert "Merge pull request #76 from areed/k8s-proxy"

---

install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-node-join.sh
install_scripts/templates/kubernetes-yml-generate.sh

This reverts commit 4b545d7daf95219375eb8eba0626ab07c4059f11.

Revert "Revert "Merge pull request #76 from areed/k8s-proxy" (#95)"

---

install_scripts/app.py
install_scripts/templates/kubernetes-yml-generate.sh

Don't use PROXY_ADDRESS from the environment.

http_proxy param to k8s yaml generate [ch10209]

---

install_scripts/app.py
install_scripts/helpers.py
install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-yml-generate.sh

Add a compatibility endpoint to check k8s version.
Update the deploy.yml endpoint with latest params.

auto-upgrade replicated k8s

---

install_scripts/templates/kubernetes-init.sh
install_scripts/templates/kubernetes-yml-generate.sh

Encryption is enabled unless the network-encrypt=0 param is passed.
On kernels below 4.2 print a warning that fast datapath will not be
used when encryption is enabled.

configure weave encryption

---

install_scripts/app.py
install_scripts/helpers.py
install_scripts/templates/error/compose_404.yml
install_scripts/templates/resolve-route.sh

Return a nice bash script-like 404 for bad and/or misspelled routes.

resolve route

---

bundles/k8s-containers/mk-image-cache-lst-v1.11.1
bundles/k8s-containers/mk-image-cache-lst-v1.9.3
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

Also fix airgap label master node name.

update rook and weave k8s yaml specs

---

install_scripts/app.py
install_scripts/templates/kubernetes/node-join.sh
install_scripts/templates/swarm/worker-join.sh

Add the custom cert to `/etc/docker/certs.d` so Docker can pull images from Replicated on-prem registry.

Install custom cert (if used).

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/kubernetes/node-upgrade.sh

Maybe restore /var/lib/kubelet/kubeadm-env.flags

Don't lookup nodes during upgrade

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh

kubectl drain timeouts

---

install_scripts/templates/common/kubernetes-upgrade.sh

Skip the recommended kubectl drain step. This is probably recommended to
prevent downtime when upgrading a cluster with enough nodes to run the
workload while each node is upgraded invidually, but in practice the
extra load of rebalancing pods and restarting Rook was found to cause
failures and longer downtime.
Fix the missing kubeadm-flags.env file on remote nodes. In kubeadm 1.11,
this file is how the kubelet is configured to use CNI plugins and run
with the correct cgroup driver.

Fix k8s cluster upgrades

---

install_scripts/templates/common/kubernetes-upgrade.sh

Accidentally deleted in earlier PR.
Also remove extra kubelet restart.

restore kubeadm upgrade node config

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/node-join.sh
install_scripts/templates/kubernetes/node-upgrade.sh

Load required kernel modules and configure kube-proxy through the
kubeadm config file.
Also ask to disable firewalld, but continue if permission is denied.

Use ipvs mode for kube-proxy

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh

see ch [14345](https://app.clubhouse.io/replicated/story/14345/flag-to-disable-the-reset-warning-message-associated-with-the-k8s-replicated-uninstall) for details

force reset flag for kubernetes + replicated uninstall

---

install_scripts/templates/common/docker-install.sh
install_scripts/templates/kubernetes/init.sh

Continue if yum repo does not have docker available.
Fix race condition in coredns patch.

fix online install for RHEL 7.4

---

install_scripts/templates/replicated-2.0.sh
install_scripts/templates/replicated-init-aws-ubuntu1404.sh
install_scripts/templates/replicated-operator.sh
install_scripts/templates/upstart/replicated-operator-stop.conf
install_scripts/templates/upstart/replicated-operator.conf
install_scripts/templates/upstart/replicated-stop.conf
install_scripts/templates/upstart/replicated-ui-stop.conf
install_scripts/templates/upstart/replicated-ui.conf
install_scripts/templates/upstart/replicated.conf

This reverts commit 7c20f64fbaff075d0cae9a97c56ad67cc81347d3.

Revert "Revert Docker restart policy on sysvinit docker service (#210)"

---

install_scripts/templates/common/kubernetes.sh

poll for Rook plugin

---

install_scripts/templates/common/docker-install.sh

When `no-ce-on-ee` flag is used with the installer, and docker is already installed, the installer should not notify the user that docker will upgraded to 17.12.1 (or any current default version) because the upgrade will be skipped.
[ch15392]

Fix upgrading docker on RHEL

---

install_scripts/templates/replicated-2.0.sh
install_scripts/templates/replicated-operator.sh
install_scripts/templates/swarm/init.sh
install_scripts/templates/swarm/worker-join.sh

This reverts commit 017290c4984a0bf3c3d304c469259cbbc5e0e606.

Revert "revert to no firewalld check on native and swarm installs"

---

install_scripts/templates/kubernetes/init.sh
install_scripts/templates/kubernetes/yml-generate.sh

Delete old Contour DaemonSet if found.

don't pull Contour images in airgap

---

install_scripts/app.py
install_scripts/helpers.py
install_scripts/templates/common/docker-install.sh
install_scripts/templates/docker-install/17-12-ce.sh
install_scripts/templates/docker-install/18-09-ce.sh
kustomize/overlays/dev/deployment.yaml

Docker 18.09

---

bundles/docker-rhel7/Dockerfile
bundles/docker-rhel7/Makefile
bundles/docker-ubuntu1604/Makefile
bundles/docker-ubuntu1804/.gitignore
bundles/docker-ubuntu1804/Dockerfile
bundles/docker-ubuntu1804/Makefile
install_scripts/app.py
install_scripts/helpers.py
install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh

Upgrade docker to 18.06.1 since 17X aren't available for Ubuntu 18.

K8s with Ubuntu 18.04

---

install_scripts/app.py
install_scripts/helpers.py
install_scripts/templates/common/replicated.sh
install_scripts/templates/swarm/docker-compose-generate.sh
install_scripts/templates/swarm/init.sh
install_scripts/templates/swarm/worker-join.sh

Run Replicated Swarm services as replicated:docker by id. If the docker group ID is different on a remote node, operator on that node will crash attempting to mount the docker socket. It doesn't matter whether the remote node has a user with the same id as the replicated user created on the master.

Swarm non root

---

install_scripts/templates/common/cli-script.sh
install_scripts/templates/kubernetes/migrate.sh

/usr/local/bin is not in the sudo path on some systems

absolute path of replicatedctl

---

install_scripts/app.py

api-service-address default is emtpy

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/migrate.sh

The kubernetes-migrate script calls this function before Kubernetes is
installed.

check for kubectl command

---

install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/init.sh
kustomize/overlays/dev/deployment.yaml

* prompt to run upgrade script on remote masters
* don't do partial upgrades in initKube
* don't upgrade Weave and Contour versions in airgap because the images won't be available on remote nodes

patch upgrade Kubernetes HA

---

install_scripts/templates/common/kubernetes.sh
install_scripts/templates/kubernetes/yml-generate.sh

Also fix rek-operator affinity yaml

Multi line exec start [ch20064]

---

install_scripts/templates/kubernetes/yaml/rook-1-0-system.yml

This reverts commit b50d21c9cff9a76e86d54cf191a242bd46aadf58.

Revert "rook v1.0.0 (#374)"

---

install_scripts/templates/common/kubernetes.sh
kustomize/overlays/staging-dev/deployment.yaml

Also drain ceph operator and mds pods.

allow app to remain running on ha clusters on reboot

---

install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh

This reverts commit 1047f6cc59e909441154915e728ede58581f8b79.

Revert "RHEL 7 7 support [ch21008]"

---

install_scripts/templates/common/docker-install.sh
install_scripts/templates/common/kubernetes-upgrade.sh
install_scripts/templates/common/kubernetes.sh

Reverts replicatedhq/replicated-installer#428

Revert "Revert "RHEL 7 7 support [ch21008]""

---

install_scripts/templates/common/ip-address.sh

url from https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#retrieving-public-ip-address

fallback to azure metadata service when discovering public IPs

---

install_scripts/templates/docker-install/17-03-ce.sh
install_scripts/templates/docker-install/17-06-ce.sh

installs are still broken prior to docker-ce (17.). Also this will not install non-lte versions like 17.05

Fix docker 17.03 and 17.06 installs, use 19.03 scripts

---

install_scripts/templates/common/kubernetes.sh

this makes it much easier to determine where a command hung

log the install of the aka-reboot service

---

install_scripts/templates/common/docker-install.sh

see http://mirror.centos.org/centos/8/extras/x86_64/os/, http://mirror.centos.org/centos/7/extras/x86_64/
and https://www.centos.org/keys/#centos-official-key + https://www.centos.org/keys/#centos-7-signing-key for key locations

use centos 7 key and extras repo on 7, 8 on 8

---

bundles/k8s-containers/Makefile

```
cd /home/circleci/go/src/github.com/linuxkit/linuxkit && \
git checkout v0.7 && \
make local-build && \
cp ./bin/linuxkit /home/circleci/go/bin/linuxkit
/bin/sh: 1: cd: can't cd to /home/circleci/go/src/github.com/linuxkit/linuxkit
```

fix k8s-containers bundle build

---

install_scripts/templates/kubernetes/yml-generate.sh
install_scripts/templates/replicated-2.0.sh
install_scripts/templates/swarm/docker-compose-generate.sh
kustomize/overlays/okteto/deployment.tmpl.yaml

Add HTTPS_PROXY variable to replicated container

---

install_scripts/templates/replicated-2.0.sh
install_scripts/templates/replicated-operator.sh

also only add readonly flag if the var is set

update replicated-ui-opts on upgrade

---

install_scripts/app.py
install_scripts/helpers.py

Adds handler for ACME challenge

Use HTTP/ACME challenge for TLS validation
